# Generated by Django 2.1.4 on 2018-12-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('homeAddress', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('phoneNo', models.IntegerField(max_length=128)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
